// 漢字マスター - Japanese Characters Database
const HIRAGANA = [
  // Vowels
  { char: 'あ', romaji: 'a', group: 'vowels', mnemonic: 'Looks like a person crossing a river' },
  { char: 'い', romaji: 'i', group: 'vowels', mnemonic: 'Two lines standing side by side' },
  { char: 'う', romaji: 'u', group: 'vowels', mnemonic: 'A hook pulling something up' },
  { char: 'え', romaji: 'e', group: 'vowels', mnemonic: 'Looks like an energetic dancer' },
  { char: 'お', romaji: 'o', group: 'vowels', mnemonic: 'A golf ball on a tee' },
  // K-row
  { char: 'か', romaji: 'ka', group: 'k-row', mnemonic: 'A knife cutting' },
  { char: 'き', romaji: 'ki', group: 'k-row', mnemonic: 'A key' },
  { char: 'く', romaji: 'ku', group: 'k-row', mnemonic: 'A bird beak' },
  { char: 'け', romaji: 'ke', group: 'k-row', mnemonic: 'A keg of beer' },
  { char: 'こ', romaji: 'ko', group: 'k-row', mnemonic: 'Two horizontal lines like a cot' },
  // S-row
  { char: 'さ', romaji: 'sa', group: 's-row', mnemonic: 'A samurai sword' },
  { char: 'し', romaji: 'shi', group: 's-row', mnemonic: 'A fishing hook' },
  { char: 'す', romaji: 'su', group: 's-row', mnemonic: 'A swinging lasso' },
  { char: 'せ', romaji: 'se', group: 's-row', mnemonic: 'A mouth saying something' },
  { char: 'そ', romaji: 'so', group: 's-row', mnemonic: 'A zigzag sewing stitch' },
  // T-row
  { char: 'た', romaji: 'ta', group: 't-row', mnemonic: 'Letters t and a combined' },
  { char: 'ち', romaji: 'chi', group: 't-row', mnemonic: 'A cheerleader' },
  { char: 'つ', romaji: 'tsu', group: 't-row', mnemonic: 'A tsunami wave' },
  { char: 'て', romaji: 'te', group: 't-row', mnemonic: 'A hand reaching out' },
  { char: 'と', romaji: 'to', group: 't-row', mnemonic: 'A toe stubbing' },
  // N-row
  { char: 'な', romaji: 'na', group: 'n-row', mnemonic: 'A knot being tied' },
  { char: 'に', romaji: 'ni', group: 'n-row', mnemonic: 'A needle and thread' },
  { char: 'ぬ', romaji: 'nu', group: 'n-row', mnemonic: 'Noodles in a bowl' },
  { char: 'ね', romaji: 'ne', group: 'n-row', mnemonic: 'A snail (Nelly)' },
  { char: 'の', romaji: 'no', group: 'n-row', mnemonic: 'A "No" sign circle' },
  // H-row
  { char: 'は', romaji: 'ha', group: 'h-row', mnemonic: 'A person laughing "ha!"' },
  { char: 'ひ', romaji: 'hi', group: 'h-row', mnemonic: 'A smiling mouth saying "hee"' },
  { char: 'ふ', romaji: 'fu', group: 'h-row', mnemonic: 'Mount Fuji' },
  { char: 'へ', romaji: 'he', group: 'h-row', mnemonic: 'A mountain peak' },
  { char: 'ほ', romaji: 'ho', group: 'h-row', mnemonic: 'A house with chimney' },
  // M-row
  { char: 'ま', romaji: 'ma', group: 'm-row', mnemonic: 'Mama with a hat' },
  { char: 'み', romaji: 'mi', group: 'm-row', mnemonic: 'The number 21' },
  { char: 'む', romaji: 'mu', group: 'm-row', mnemonic: 'A cow mooing' },
  { char: 'め', romaji: 'me', group: 'm-row', mnemonic: 'An eye looking at me' },
  { char: 'も', romaji: 'mo', group: 'm-row', mnemonic: 'More fish hooks' },
  // Y-row
  { char: 'や', romaji: 'ya', group: 'y-row', mnemonic: 'A yak' },
  { char: 'ゆ', romaji: 'yu', group: 'y-row', mnemonic: 'A U-turn' },
  { char: 'よ', romaji: 'yo', group: 'y-row', mnemonic: 'A yo-yo' },
  // R-row
  { char: 'ら', romaji: 'ra', group: 'r-row', mnemonic: 'A rabbit running' },
  { char: 'り', romaji: 'ri', group: 'r-row', mnemonic: 'Two reeds' },
  { char: 'る', romaji: 'ru', group: 'r-row', mnemonic: 'A loop' },
  { char: 'れ', romaji: 're', group: 'r-row', mnemonic: 'A person reaching' },
  { char: 'ろ', romaji: 'ro', group: 'r-row', mnemonic: 'A road' },
  // W-row + N
  { char: 'わ', romaji: 'wa', group: 'w-row', mnemonic: 'A water swirl' },
  { char: 'を', romaji: 'wo', group: 'w-row', mnemonic: 'A warrior' },
  { char: 'ん', romaji: 'n', group: 'w-row', mnemonic: 'The end of the alphabet' },
];

const KATAKANA = [
  { char: 'ア', romaji: 'a', group: 'vowels', mnemonic: 'An antenna' },
  { char: 'イ', romaji: 'i', group: 'vowels', mnemonic: 'An eagle' },
  { char: 'ウ', romaji: 'u', group: 'vowels', mnemonic: 'An inbox tray' },
  { char: 'エ', romaji: 'e', group: 'vowels', mnemonic: 'An elevator' },
  { char: 'オ', romaji: 'o', group: 'vowels', mnemonic: 'An opera singer' },
  { char: 'カ', romaji: 'ka', group: 'k-row', mnemonic: 'A sharp katana' },
  { char: 'キ', romaji: 'ki', group: 'k-row', mnemonic: 'A key shape' },
  { char: 'ク', romaji: 'ku', group: 'k-row', mnemonic: 'A corner' },
  { char: 'ケ', romaji: 'ke', group: 'k-row', mnemonic: 'A crooked K' },
  { char: 'コ', romaji: 'ko', group: 'k-row', mnemonic: 'A corner angle' },
  { char: 'サ', romaji: 'sa', group: 's-row', mnemonic: 'A sardine' },
  { char: 'シ', romaji: 'shi', group: 's-row', mnemonic: 'A smiley face ;)' },
  { char: 'ス', romaji: 'su', group: 's-row', mnemonic: 'A ski slope' },
  { char: 'セ', romaji: 'se', group: 's-row', mnemonic: 'A say balloon' },
  { char: 'ソ', romaji: 'so', group: 's-row', mnemonic: 'Like ン but different angle' },
  { char: 'タ', romaji: 'ta', group: 't-row', mnemonic: 'A table' },
  { char: 'チ', romaji: 'chi', group: 't-row', mnemonic: 'A cheerful 5' },
  { char: 'ツ', romaji: 'tsu', group: 't-row', mnemonic: 'A smiley face :)' },
  { char: 'テ', romaji: 'te', group: 't-row', mnemonic: 'A telephone pole' },
  { char: 'ト', romaji: 'to', group: 't-row', mnemonic: 'A totem pole' },
  { char: 'ナ', romaji: 'na', group: 'n-row', mnemonic: 'A narwhal horn' },
  { char: 'ニ', romaji: 'ni', group: 'n-row', mnemonic: 'Knee lines' },
  { char: 'ヌ', romaji: 'nu', group: 'n-row', mnemonic: 'Noodle swirl' },
  { char: 'ネ', romaji: 'ne', group: 'n-row', mnemonic: 'A net' },
  { char: 'ノ', romaji: 'no', group: 'n-row', mnemonic: 'A nose line' },
  { char: 'ハ', romaji: 'ha', group: 'h-row', mnemonic: 'A hat top' },
  { char: 'ヒ', romaji: 'hi', group: 'h-row', mnemonic: 'A heel' },
  { char: 'フ', romaji: 'fu', group: 'h-row', mnemonic: 'A hood' },
  { char: 'ヘ', romaji: 'he', group: 'h-row', mnemonic: 'Same as hiragana へ' },
  { char: 'ホ', romaji: 'ho', group: 'h-row', mnemonic: 'A holy cross' },
  { char: 'マ', romaji: 'ma', group: 'm-row', mnemonic: 'A mask' },
  { char: 'ミ', romaji: 'mi', group: 'm-row', mnemonic: 'Three lines = mi (3)' },
  { char: 'ム', romaji: 'mu', group: 'm-row', mnemonic: 'A moose head' },
  { char: 'メ', romaji: 'me', group: 'm-row', mnemonic: 'An X marks me' },
  { char: 'モ', romaji: 'mo', group: 'm-row', mnemonic: 'More lines' },
  { char: 'ヤ', romaji: 'ya', group: 'y-row', mnemonic: 'A yak horn' },
  { char: 'ユ', romaji: 'yu', group: 'y-row', mnemonic: 'A U shape' },
  { char: 'ヨ', romaji: 'yo', group: 'y-row', mnemonic: 'A yogurt cup' },
  { char: 'ラ', romaji: 'ra', group: 'r-row', mnemonic: 'A ramp' },
  { char: 'リ', romaji: 'ri', group: 'r-row', mnemonic: 'Two rivers' },
  { char: 'ル', romaji: 'ru', group: 'r-row', mnemonic: 'Tree roots' },
  { char: 'レ', romaji: 're', group: 'r-row', mnemonic: 'A razor edge' },
  { char: 'ロ', romaji: 'ro', group: 'r-row', mnemonic: 'A robot mouth' },
  { char: 'ワ', romaji: 'wa', group: 'w-row', mnemonic: 'A wine glass' },
  { char: 'ヲ', romaji: 'wo', group: 'w-row', mnemonic: 'A trophy (wo!)' },
  { char: 'ン', romaji: 'n', group: 'w-row', mnemonic: 'Like シ but tilted' },
];

const KANJI = [
  { char: '一', romaji: 'ichi', meaning: 'one', group: 'numbers', mnemonic: 'One horizontal line = one' },
  { char: '二', romaji: 'ni', meaning: 'two', group: 'numbers', mnemonic: 'Two horizontal lines = two' },
  { char: '三', romaji: 'san', meaning: 'three', group: 'numbers', mnemonic: 'Three lines = three' },
  { char: '四', romaji: 'shi/yon', meaning: 'four', group: 'numbers', mnemonic: 'Four legs in a box' },
  { char: '五', romaji: 'go', meaning: 'five', group: 'numbers', mnemonic: 'Five strokes total' },
  { char: '六', romaji: 'roku', meaning: 'six', group: 'numbers', mnemonic: 'A person doing a split' },
  { char: '七', romaji: 'shichi/nana', meaning: 'seven', group: 'numbers', mnemonic: 'Looks like 7 rotated' },
  { char: '八', romaji: 'hachi', meaning: 'eight', group: 'numbers', mnemonic: 'Two lines opening up' },
  { char: '九', romaji: 'ku/kyuu', meaning: 'nine', group: 'numbers', mnemonic: 'A hook with a curl' },
  { char: '十', romaji: 'juu', meaning: 'ten', group: 'numbers', mnemonic: 'A cross = 10' },
  { char: '日', romaji: 'nichi/hi', meaning: 'day/sun', group: 'nature', mnemonic: 'A window showing the sun' },
  { char: '月', romaji: 'getsu/tsuki', meaning: 'month/moon', group: 'nature', mnemonic: 'A crescent moon' },
  { char: '火', romaji: 'ka/hi', meaning: 'fire', group: 'nature', mnemonic: 'A person with flames' },
  { char: '水', romaji: 'sui/mizu', meaning: 'water', group: 'nature', mnemonic: 'Water splashing' },
  { char: '木', romaji: 'moku/ki', meaning: 'tree/wood', group: 'nature', mnemonic: 'A tree with branches' },
  { char: '金', romaji: 'kin/kane', meaning: 'gold/money', group: 'nature', mnemonic: 'Gold nuggets underground' },
  { char: '土', romaji: 'do/tsuchi', meaning: 'earth/soil', group: 'nature', mnemonic: 'A cross in the ground' },
  { char: '山', romaji: 'san/yama', meaning: 'mountain', group: 'nature', mnemonic: 'Three mountain peaks' },
  { char: '川', romaji: 'sen/kawa', meaning: 'river', group: 'nature', mnemonic: 'Three streams flowing' },
  { char: '田', romaji: 'den/ta', meaning: 'rice field', group: 'nature', mnemonic: 'A divided rice field' },
  { char: '人', romaji: 'jin/hito', meaning: 'person', group: 'people', mnemonic: 'A person walking' },
  { char: '大', romaji: 'dai/ookii', meaning: 'big', group: 'people', mnemonic: 'A person stretching wide' },
  { char: '小', romaji: 'shou/chiisai', meaning: 'small', group: 'people', mnemonic: 'A small thing with dots' },
  { char: '子', romaji: 'shi/ko', meaning: 'child', group: 'people', mnemonic: 'A child with arms' },
  { char: '女', romaji: 'jo/onna', meaning: 'woman', group: 'people', mnemonic: 'A woman dancing' },
  { char: '男', romaji: 'dan/otoko', meaning: 'man', group: 'people', mnemonic: 'Strength in the field' },
  { char: '口', romaji: 'kou/kuchi', meaning: 'mouth', group: 'body', mnemonic: 'An open mouth' },
  { char: '目', romaji: 'moku/me', meaning: 'eye', group: 'body', mnemonic: 'An eye turned sideways' },
  { char: '耳', romaji: 'ji/mimi', meaning: 'ear', group: 'body', mnemonic: 'An ear shape' },
  { char: '手', romaji: 'shu/te', meaning: 'hand', group: 'body', mnemonic: 'A hand with fingers' },
  { char: '足', romaji: 'soku/ashi', meaning: 'foot/leg', group: 'body', mnemonic: 'A foot stepping' },
  { char: '上', romaji: 'jou/ue', meaning: 'up/above', group: 'direction', mnemonic: 'Arrow pointing up' },
  { char: '下', romaji: 'ka/shita', meaning: 'down/below', group: 'direction', mnemonic: 'Arrow pointing down' },
  { char: '左', romaji: 'sa/hidari', meaning: 'left', group: 'direction', mnemonic: 'Left hand working' },
  { char: '右', romaji: 'u/migi', meaning: 'right', group: 'direction', mnemonic: 'Right hand eating' },
  { char: '中', romaji: 'chuu/naka', meaning: 'middle/inside', group: 'direction', mnemonic: 'A line through the center' },
  { char: '学', romaji: 'gaku/manabu', meaning: 'study/learn', group: 'school', mnemonic: 'A child under a roof studying' },
  { char: '校', romaji: 'kou', meaning: 'school', group: 'school', mnemonic: 'A wooden school building' },
  { char: '先', romaji: 'sen/saki', meaning: 'previous/ahead', group: 'school', mnemonic: 'A person walking ahead' },
  { char: '生', romaji: 'sei/ikiru', meaning: 'life/birth', group: 'school', mnemonic: 'A plant growing from earth' },
  { char: '年', romaji: 'nen/toshi', meaning: 'year', group: 'time', mnemonic: 'Grain harvest cycle' },
  { char: '本', romaji: 'hon/moto', meaning: 'book/origin', group: 'school', mnemonic: 'A tree with roots (origin)' },
  { char: '白', romaji: 'haku/shiro', meaning: 'white', group: 'colors', mnemonic: 'A white sun ray' },
  { char: '赤', romaji: 'seki/aka', meaning: 'red', group: 'colors', mnemonic: 'Earth and fire = red' },
  { char: '青', romaji: 'sei/ao', meaning: 'blue/green', group: 'colors', mnemonic: 'The moon over life' },
  { char: '空', romaji: 'kuu/sora', meaning: 'sky/empty', group: 'nature', mnemonic: 'A cave opening to sky' },
  { char: '雨', romaji: 'u/ame', meaning: 'rain', group: 'nature', mnemonic: 'Raindrops under a cloud' },
  { char: '花', romaji: 'ka/hana', meaning: 'flower', group: 'nature', mnemonic: 'A person transforming into flower' },
  { char: '車', romaji: 'sha/kuruma', meaning: 'car/vehicle', group: 'things', mnemonic: 'A cart seen from top' },
  { char: '食', romaji: 'shoku/taberu', meaning: 'eat/food', group: 'daily', mnemonic: 'A person eating with lid on' },
];

const GROUPS = {
  hiragana: ['vowels','k-row','s-row','t-row','n-row','h-row','m-row','y-row','r-row','w-row'],
  katakana: ['vowels','k-row','s-row','t-row','n-row','h-row','m-row','y-row','r-row','w-row'],
  kanji: ['numbers','nature','people','body','direction','school','time','colors','things','daily']
};

const GROUP_NAMES = {
  'vowels': 'Samohlásky (あ行)', 'k-row': 'K-řádek (か行)', 's-row': 'S-řádek (さ行)',
  't-row': 'T-řádek (た行)', 'n-row': 'N-řádek (な行)', 'h-row': 'H-řádek (は行)',
  'm-row': 'M-řádek (ま行)', 'y-row': 'Y-řádek (や行)', 'r-row': 'R-řádek (ら行)',
  'w-row': 'W-řádek (わ行)', 'numbers': 'Čísla (数字)', 'nature': 'Příroda (自然)',
  'people': 'Lidé (人々)', 'body': 'Tělo (体)', 'direction': 'Směry (方向)',
  'school': 'Škola (学校)', 'time': 'Čas (時間)', 'colors': 'Barvy (色)',
  'things': 'Věci (物)', 'daily': 'Denní život (日常)'
};

const TUTORIAL_LESSONS = [
  { id: 'h-vowels', title: 'Hiragana: Samohlásky', type: 'hiragana', group: 'vowels', desc: 'Naučte se 5 základních samohlásek – základ celé hiragany.' },
  { id: 'h-k', title: 'Hiragana: K-řádek', type: 'hiragana', group: 'k-row', desc: 'Ka, Ki, Ku, Ke, Ko – znaky se souhláskou K.' },
  { id: 'h-s', title: 'Hiragana: S-řádek', type: 'hiragana', group: 's-row', desc: 'Sa, Shi, Su, Se, So – pozor na výjimku Shi!' },
  { id: 'h-t', title: 'Hiragana: T-řádek', type: 'hiragana', group: 't-row', desc: 'Ta, Chi, Tsu, Te, To – dvě výjimky v tomto řádku.' },
  { id: 'h-n', title: 'Hiragana: N-řádek', type: 'hiragana', group: 'n-row', desc: 'Na, Ni, Nu, Ne, No – pravidelný řádek.' },
  { id: 'h-h', title: 'Hiragana: H-řádek', type: 'hiragana', group: 'h-row', desc: 'Ha, Hi, Fu, He, Ho – pozor na Fu místo Hu!' },
  { id: 'h-m', title: 'Hiragana: M-řádek', type: 'hiragana', group: 'm-row', desc: 'Ma, Mi, Mu, Me, Mo – pravidelný řádek.' },
  { id: 'h-y', title: 'Hiragana: Y-řádek', type: 'hiragana', group: 'y-row', desc: 'Ya, Yu, Yo – pouze 3 znaky.' },
  { id: 'h-r', title: 'Hiragana: R-řádek', type: 'hiragana', group: 'r-row', desc: 'Ra, Ri, Ru, Re, Ro – R se vyslovuje mezi R a L.' },
  { id: 'h-w', title: 'Hiragana: W-řádek + N', type: 'hiragana', group: 'w-row', desc: 'Wa, Wo, N – poslední znaky hiragany.' },
  { id: 'k-vowels', title: 'Katakana: Samohlásky', type: 'katakana', group: 'vowels', desc: 'Stejné zvuky, ostřejší tahy – katakana samohlásky.' },
  { id: 'k-k', title: 'Katakana: K-řádek', type: 'katakana', group: 'k-row', desc: 'Ka, Ki, Ku, Ke, Ko v katakaně.' },
  { id: 'k-s', title: 'Katakana: S-řádek', type: 'katakana', group: 's-row', desc: 'Pozor na záměnu シ (shi) a ツ (tsu)!' },
  { id: 'k-t', title: 'Katakana: T-řádek', type: 'katakana', group: 't-row', desc: 'Katakanový T-řádek.' },
  { id: 'k-n', title: 'Katakana: N-řádek', type: 'katakana', group: 'n-row', desc: 'Katakanový N-řádek.' },
  { id: 'k-rest', title: 'Katakana: Zbývající', type: 'katakana', group: 'h-row', desc: 'Dokončete katakanu – H, M, Y, R, W řádky.' },
  { id: 'kanji-num', title: 'Kanji: Čísla 1-10', type: 'kanji', group: 'numbers', desc: 'Prvních 10 kanji – čísla jsou nejsnazší start.' },
  { id: 'kanji-nat', title: 'Kanji: Příroda', type: 'kanji', group: 'nature', desc: 'Slunce, měsíc, oheň, voda a další přírodní kanji.' },
  { id: 'kanji-ppl', title: 'Kanji: Lidé', type: 'kanji', group: 'people', desc: 'Člověk, velký, malý, dítě, žena, muž.' },
  { id: 'kanji-body', title: 'Kanji: Tělo', type: 'kanji', group: 'body', desc: 'Ústa, oči, uši, ruce a nohy.' },
];
